### ISSUE TITLE
Which would you rather fight?

### ISSUE THREAD

**Issue by heldeen** [aaronfrost/ama#3]
Would you rather fight 100 duck sized horses or one horse sized duck?

**Comment by aaronfrost** [comment]
I thought about this questions very seriously throughout the entire afternoon. It is a very serious thing to consider. I considered my answer while I was driving. Again while making dinner. Then later while reading to the kids, and later still while answering some tweets. It's finally time to make some sense of the violent storm of potentially coherent and extremely fallible thoughts that I have been able to scrap together this far.

TL;DR - I would rather fight 100 duck-sized horses. 

I did not come to this decision lightly. For a large part of the day, I found myself unable to approach a solution in a way that would allow me to formulate an answer. But it was in that moment that I had my first realization: I needed to be one with the duck! I needed to be ONE with the duck. Now in a biblical sense, that is totally illegal and I could go to jail if I even tweeted that I wanted to be one with the duck. So out of the gate, being one with the duck sounds like a horrible idea. And I think that it sounds horrible because it is an absolute horrible crap-of-an-idea. So then I came to my second realization: being one with the duck is a bad idea! Desperate, I started to grasp at ideas. I felt close to a solution, but couldn't see it clearly. Did I need to be one with the horse maybe? Perhaps I needed to be one with the horse. I definitely needed to explore this path more. While being one with the horse is also illegal and disturbing, I thought of the Minotaur. These thoughts seemed to set my mind at ease: that the Minotaur was a perfect combination of human and horse. And if such a perfect combination could exist in the legends and myths... then maybe, JUST MAYBE, they could exist as an answer to my problem. But then I realized that the Minotaur is not part horse. It is part bull. That's right. It has absolutely nothing to do with a horse. If you were reading this and were nodding your head "yes" in agreement when you first read my mention of the Minotaur, then please know you are just as pathetic as I am for thinking that the Minotaur was part bull. That is so rich!!!! How dare you insult the Minotaur in such a way?! Back to the story. Again, I found myself back at square one. 100 horse-ducks, or a Duck-horse??? Which to chose in a fight. 

Here is the thing: I am going to lose this fight. I simply cannot win. I am hopelessly and pathetically un-equipped for this hypothetical scenario that @heldeen has put me in. This is a lose-lose for all involved. It's a no-win scenario. But like the famous militant hero of our times, James Kirk, I don't believe in no-win scenarios. There had to be a scenario where I could pull out a victory. What if I could lose but not die? Do you see my point? What if I could take on the duck-horse or the 100 horse-ducks and somehow survive? Would simply surviving and living to see another day be enough to consider that a victory (even if only kind of)? My short answer: Yes. Yes it would be enough to consider that a victory of sorts. 

Ducks are just simply violent. They are one of the only animals who have a famous martial arts technique named after them. You've got crouching tiger. And you've got hidden dragon. And then you've got my favorite: duck. It's all I know how to do. I don't know how to do those other things. They simply sound too fancy. I might be perfectly able to do them, however. Among the things I am good at, I have always considered myself above-average on agility and flexibility, considering that I am a rather large guy. Usually people think that it may be my beard that gives me that advantage, but I can't be sure. But the "duck"? I can duck like a champ. 

I simply don't think that I could survive the bill-power of a duck-horse. I think that I could survive the bill power of 100 horse-ducks. So it is with a full and complete understanding that I will likely need skin-grafts on over 95% of my body, I say that I would rather take on all 100 of the horse ducks. I think that I could assume the fetal position, hide my face long enough for them to go away, crawl back to safety afterwards, get the skin grafts. And then get back to business as usual. 

Thoughts? Did you decide that the duck-horse is a better plan?

**Comment by aashishkoirala** [comment]
Minotaur = bull + man, not horse + man. I believe you're thinking of a centaur.

**Comment by heldeen** [comment]
An insightful answer from todays thinking man @aaronfrost. Thanks! It was a pleasure to read.

I too would fight the 100 duck sized horses because ducks are terribly mean and violent. I would certainly loose almost instantly to the large horse sized duck.  :)
